import {
  setCapabilities,
  stripTerminalSequences,
  visibleWidth,
} from '@earendil-works/pi-tui'
import { renderLayoutFrame } from '@earendil-works/pi-tui/dist/layout.js'
import { afterEach, describe, expect, it } from 'vitest'
import {
  ConversationDocumentComponent,
  ConversationRoot,
  layoutConversationComposer,
  layoutConversationDashboard,
  sanitizeMarkdownSource,
  type ConversationNode,
  type ConversationSurface,
} from '../src/ui/conversation.ts'
import { createDshTuiTheme } from '../src/ui/theme.ts'

const mono = createDshTuiTheme({ preset: 'mono' }, {
  colorSupported: false,
  noColor: true,
  dumbTerminal: false,
})

function assistant(
  key: string,
  text: string,
  reasoning = '',
): ConversationNode {
  return {
    kind: 'assistant',
    key,
    revision: `${text.length}:${reasoning.length}`,
    text,
    reasoning,
    ...(reasoning === '' ? {} : { reasoningSummary: 'THINKING · 1 lines' }),
  }
}

function surface(
  sessionId: string,
  bindingEpoch: number,
  nodes: readonly ConversationNode[],
  reasoningExpanded = false,
): ConversationSurface {
  return {
    sessionId,
    bindingEpoch,
    header: `DSH-TUI · ${sessionId}`,
    nodes,
    composer: '',
    composerColumn: 0,
    composerPrefix: '> ',
    footer: 'Ctrl+F search',
    reasoningExpanded,
  }
}

afterEach(() => {
  setCapabilities({ images: null, trueColor: false, hyperlinks: false })
})

describe('conversation document', () => {
  it('keeps reasoning folded away from final Markdown until explicitly expanded', () => {
    const document = new ConversationDocumentComponent(mono)
    document.setNodes([assistant('assistant:1:1', '**final**', 'private reasoning')], false)
    const folded = stripTerminalSequences(document.render(40).join('\n'))
    expect(folded).toContain('THINKING · 1 lines')
    expect(folded).toContain('final')
    expect(folded).not.toContain('private reasoning')
    expect(folded).not.toContain('Assistant:')

    document.setNodes([assistant('assistant:1:1', '**final**', 'private reasoning')], true)
    const expanded = stripTerminalSequences(document.render(40).join('\n'))
    expect(expanded).toContain('private reasoning')
    expect(expanded).toContain('final')
  })

  it('sanitizes hostile controls and only emits OSC 8 for validated links', () => {
    setCapabilities({ images: null, trueColor: true, hyperlinks: true })
    const document = new ConversationDocumentComponent(mono)
    document.setNodes([{
      kind: 'user',
      key: 'event:1',
      revision: '1',
      text: [
        '\x1b]52;c;owned\x07safe',
        '[web](https://example.com)',
        '[bad](javascript:alert(1))',
        '[file](file:///C:/secret)',
      ].join('\n'),
    }], false)
    const output = document.render(80).join('\n')
    expect(output).not.toContain(']52;')
    expect(output).toContain('\x1b]8;;https://example.com\x1b\\')
    expect(output).not.toContain('\x1b]8;;javascript:')
    expect(output).not.toContain('\x1b]8;;file:')
    expect(stripTerminalSequences(output)).toContain('bad (javascript:alert(1))')
  })

  it('removes OSC 8 generated by a GFM bare URL beyond the trusted length bound', () => {
    setCapabilities({ images: null, trueColor: true, hyperlinks: true })
    const bare = 'https://example.com/' + 'x'.repeat(2050)
    const document = new ConversationDocumentComponent(mono)
    document.setNodes([{
      kind: 'assistant',
      key: 'assistant:bare:1',
      revision: '1',
      text: bare,
    }], false)

    const output = document.render(4096).join('\n')
    expect(output).not.toContain(`\x1b]8;;${bare}`)
    expect(stripTerminalSequences(output)).toContain(bare)
  })

  it('keeps a semantic anchor when a draft is replaced by its final row', () => {
    const document = new ConversationDocumentComponent(mono)
    const draft: ConversationNode = {
      kind: 'assistant-draft',
      key: 'assistant:2:3',
      revision: '10',
      text: 'streaming line one\nstreaming line two',
      reasoning: 'thinking',
      reasoningSummary: 'THINKING · streaming',
    }
    document.setNodes([draft], false)
    document.render(20)
    const anchor = document.anchorAt(1)
    expect(anchor?.nodeKey).toBe('assistant:2:3')

    document.setNodes([assistant('assistant:2:3', 'final line', 'thinking')], false)
    document.render(20)
    expect(document.scrollTopFor(anchor!)).toBeGreaterThanOrEqual(0)
  })

  it('obeys terminal cell width for CJK, emoji, and narrow gutters', () => {
    const document = new ConversationDocumentComponent(mono)
    document.setNodes([{
      kind: 'user',
      key: 'event:1',
      revision: '1',
      text: '中文🙂 very-long-token-without-spaces-0123456789',
    }], false)
    for (const width of [1, 2, 3, 8, 20]) {
      for (const line of document.render(width)) {
        expect(visibleWidth(line)).toBeLessThanOrEqual(width)
      }
    }
  })

  it('restores per-session scroll anchors and rejects an older binding epoch', () => {
    const root = new ConversationRoot(mono, () => {})
    const many = Array.from({ length: 12 }, (_, index) => assistant(
      `assistant:${index}:1`,
      `message ${index}`,
    ))
    root.setSurface(surface('A', 2, many))
    let lines = root.document.render(30)
    root.scroll.updateLayout(lines.length, 5, () => {})
    root.restoreAfterLayout()
    root.scroll.scrollTo(4, { disableFollow: true })

    root.setSurface(surface('B', 3, [assistant('assistant:b:1', 'session b')]))
    lines = root.document.render(30)
    root.scroll.updateLayout(lines.length, 5, () => {})
    root.restoreAfterLayout()

    root.setSurface(surface('A', 4, many))
    lines = root.document.render(30)
    root.scroll.updateLayout(lines.length, 5, () => {})
    root.restoreAfterLayout()
    expect(root.scroll.scrollTop).toBeGreaterThan(0)

    root.setSurface(surface('A', 1, [assistant('stale', 'stale')]))
    expect(root.document.render(30).join('\n')).not.toContain('stale')
    root.dispose()
  })

  it('renders every card role and status without leaking controls or cell width', () => {
    const document = new ConversationDocumentComponent(mono)
    const nodes: readonly ConversationNode[] = [
      {
        kind: 'tool',
        key: 'tool:failed',
        revision: '1',
        label: 'TOOL failed',
        status: 'failed',
        lines: ['boom\x1b[31m\u0007', '中文🙂'],
      },
      {
        kind: 'tool',
        key: 'tool:done',
        revision: '1',
        label: 'TOOL done',
        status: 'done',
        lines: [],
      },
      {
        kind: 'command',
        key: 'command:warning',
        revision: '1',
        label: 'CMD warning',
        status: 'warning',
        lines: ['retry'],
      },
      {
        kind: 'command',
        key: 'command:running',
        revision: '1',
        label: 'CMD running',
        status: 'running',
        lines: ['working'],
      },
      {
        kind: 'interaction',
        key: 'interaction:plain',
        revision: '1',
        label: 'QUESTION',
        lines: ['answer'],
      },
      {
        kind: 'activity',
        key: 'activity:stopping',
        revision: '1',
        label: 'ACTIVITY stopping',
        status: 'stopping',
        lines: ['waiting for producer cleanup'],
      },
      {
        kind: 'activity',
        key: 'activity:killed',
        revision: '1',
        label: 'ACTIVITY killed',
        status: 'killed',
        lines: ['cancelled'],
      },
      {
        kind: 'notice',
        key: 'notice:1',
        revision: '1',
        lines: ['notice\twith\nline'],
      },
      {
        kind: 'empty',
        key: 'empty:1',
        revision: '1',
        lines: ['Cordis Whale'],
      },
    ]
    document.setNodes(nodes, false)

    const full = stripTerminalSequences(document.render(40).join('\n'))
    expect(full).toContain('TOOL failed')
    expect(full).toContain('× FAILED')
    expect(full).toContain('TOOL done')
    expect(full).toContain('✓ DONE')
    expect(full).toContain('CMD warning')
    expect(full).toContain('! ACTION')
    expect(full).toContain('CMD running')
    expect(full).toContain('● RUNNING')
    expect(full).toContain('QUESTION')
    expect(full).toContain('ACTIVITY stopping')
    expect(full).toContain('◌ STOPPING')
    expect(full).toContain('ACTIVITY killed')
    expect(full).toContain('■ KILLED')
    expect(full).toContain('notice  with line')
    expect(full).not.toContain('\x1b')
    expect(full).not.toMatch(/[\u0000-\u0009\u000b-\u001f\u007f-\u009f]/u)

    for (const width of [1, 7, 40]) {
      for (const line of document.render(width)) {
        expect(visibleWidth(line)).toBeLessThanOrEqual(width)
      }
    }
  })

  it('keeps empty and interrupted assistant output explicit and exercises rich Markdown safely', () => {
    setCapabilities({ images: null, trueColor: true, hyperlinks: true })
    const document = new ConversationDocumentComponent(createDshTuiTheme())
    document.setNodes([
      {
        kind: 'assistant',
        key: 'assistant:empty',
        revision: '1',
        text: '',
        interrupted: true,
      },
      {
        kind: 'user',
        key: 'user:markdown',
        revision: '1',
        text: [
          '# Heading',
          '',
          '**bold** *italic* ~~strike~~ `inline` [safe](https://example.com "title")',
          '',
          '> quote',
          '',
          '- list item',
          '',
          '---',
          '',
          '```ts',
          'const value = 1',
          '```',
        ].join('\n'),
      },
      {
        kind: 'user',
        key: 'user:empty',
        revision: '1',
        text: '',
      },
      {
        kind: 'assistant-draft',
        key: 'assistant:summary-only',
        revision: '1',
        text: 'waiting',
        reasoningSummary: 'THINKING · waiting',
        omittedChunkCount: 4,
      },
    ], true)

    const output = stripTerminalSequences(document.render(64).join('\n'))
    expect(output).toContain('[No final answer]')
    expect(output).toContain('[interrupted]')
    expect(output).toContain('Heading')
    expect(output).toContain('const value = 1')
    expect(output).toContain('safe')
    expect(output).toContain('4 earlier stream chunks omitted')
    document.invalidate()
    expect(stripTerminalSequences(document.render(64).join('\n'))).toContain('list item')
  })

  it('maintains anchors across reflow and defines empty, fallback, and clamped anchor behavior', () => {
    const document = new ConversationDocumentComponent(mono)
    expect(document.anchorAt(0)).toBeUndefined()
    expect(document.scrollTopFor({ nodeKey: 'missing', intraVisualLine: 9, ordinal: 0 })).toBe(0)

    document.setNodes([
      assistant('assistant:first', 'first line\nsecond line\nthird line'),
      assistant('assistant:second', 'tail'),
    ], false)
    document.render(20)
    const pastEnd = document.anchorAt(10_000)!
    expect(pastEnd.nodeKey).toBe('assistant:second')
    expect(document.scrollTopFor({
      nodeKey: 'assistant:first',
      intraVisualLine: 10_000,
      ordinal: 0,
    })).toBeLessThan(document.scrollTopFor(pastEnd))
    expect(document.scrollTopFor({
      nodeKey: 'removed',
      intraVisualLine: 0,
      ordinal: 99,
    })).toBeGreaterThan(0)

    document.setNodes([assistant('assistant:second', 'tail revised')], false)
    document.render(12)
    document.invalidate()
    document.setNodes([{
      kind: 'future-presentation',
      key: 'future:1',
      revision: '1',
    } as unknown as ConversationNode], false)
    expect(document.render(12)).toEqual([])
    document.clear()
    expect(document.render(12)).toEqual([])
    expect(document.anchorAt(0)).toBeUndefined()
  })
})

describe('conversation viewport state', () => {
  function layout(root: ConversationRoot, width = 30, height = 5): void {
    const lines = root.document.render(width)
    root.scroll.updateLayout(lines.length, height, () => {})
    root.restoreAfterLayout()
  }

  it('freezes on history, reports unseen output, and resumes follow for a new user tail', () => {
    const root = new ConversationRoot(mono, () => {})
    const initial = Array.from({ length: 16 }, (_, index) => assistant(
      `assistant:${index}`,
      `message ${index}`,
    ))
    root.setSurface({ ...surface('A', 1, initial), footer: '' })
    layout(root)
    expect(root.scroll.isFollowingEnd).toBe(true)

    root.scroll.scrollTo(4, { disableFollow: true })
    const frozenTop = root.scroll.scrollTop
    root.setSurface({
      ...surface('A', 1, [
        ...initial,
        assistant('assistant:new', 'late output'),
      ]),
      footer: '',
    })
    layout(root)
    expect(root.scroll.isFollowingEnd).toBe(false)
    expect(root.scroll.scrollTop).toBe(frozenTop)
    expect(stripTerminalSequences(root.component.render(30).join('\n')))
      .toContain('New output')

    const userTail: ConversationNode = {
      kind: 'user',
      key: 'user:new',
      revision: '1',
      text: 'continue',
    }
    root.setSurface({ ...surface('A', 1, [...initial, userTail]), footer: '' })
    layout(root)
    expect(root.scroll.isFollowingEnd).toBe(true)
    expect(stripTerminalSequences(root.component.render(30).join('\n')))
      .not.toContain('New output')
    root.dispose()
  })

  it('preserves a semantic anchor through resize capture and same-session epoch replacement', () => {
    const root = new ConversationRoot(mono, () => {})
    const nodes = Array.from({ length: 14 }, (_, index) => assistant(
      `assistant:${index}`,
      `long message ${index} with words that wrap at narrow widths`,
    ))
    root.setSurface(surface('A', 1, nodes))
    layout(root, 36, 5)
    root.scroll.scrollTo(8, { disableFollow: true })
    const anchor = root.document.anchorAt(root.scroll.scrollTop)!

    root.captureBeforeResize()
    const narrowLines = root.document.render(18)
    root.scroll.updateLayout(narrowLines.length, 5, () => {})
    root.restoreAfterLayout()
    expect(root.document.anchorAt(root.scroll.scrollTop)?.nodeKey).toBe(anchor.nodeKey)

    root.setSurface(surface('A', 2, nodes))
    layout(root, 18, 5)
    expect(root.document.anchorAt(root.scroll.scrollTop)?.nodeKey).toBe(anchor.nodeKey)
    expect(root.restoreAfterLayout()).toBe(false)
    root.dispose()
  })

  it('bounds per-session snapshots with LRU eviction', () => {
    const root = new ConversationRoot(mono, () => {})
    const many = Array.from({ length: 12 }, (_, index) => assistant(
      `assistant:A:${index}`,
      `message ${index}`,
    ))
    root.setSurface(surface('A', 1, many))
    layout(root)
    root.scroll.scrollTo(4, { disableFollow: true })

    for (let index = 0; index < 33; index += 1) {
      root.setSurface(surface(`S${index}`, 1, [assistant(`assistant:S${index}`, `session ${index}`)]))
      layout(root)
    }

    root.setSurface(surface('A', 2, many))
    layout(root)
    expect(root.scroll.isFollowingEnd).toBe(true)
    expect(root.scroll.scrollTop).not.toBe(4)
    root.dispose()
  })

  it('projects header, dock, composer cursor, footer, and focused input as one surface', () => {
    const input: string[] = []
    const root = new ConversationRoot(mono, data => input.push(data))
    root.setSurface({
      ...surface('中文-session', 1, [assistant('assistant:1', 'answer')]),
      header: 'DSH-TUI\x1b[2J · 中文-session',
      statusline: {
        text: '◆ MODEL deepseek/high · CTX [━━━━····] 50%\u0007',
        tone: 'warning',
        segments: [
          { text: 'MODEL deepseek/high', tone: 'assistant' },
          { text: 'CTX [━━━━····] 50%\u0007', tone: 'warning' },
        ],
      },
      dock: { label: 'QUESTION', role: 'interaction', lines: ['选择🙂'] },
      dashboard: {
        label: 'WORKBENCH DASHBOARD',
        lines: [
          { text: 'GOAL active\u001b[2J', tone: 'accent' },
          { text: '● render rail\u0007', tone: 'primary' },
        ],
      },
      composer: '中文',
      composerColumn: 2,
      composerPrefix: '> ',
      composerLabel: 'PROMPT',
      composerBoxed: true,
      footer: 'Ctrl+F search\u0007',
    })
    layout(root, 24, 5)
    root.focusTarget.handleInput?.('x')
    expect(input).toEqual(['x'])
    const inside = root.component.render(24)
    expect(stripTerminalSequences(inside.join('\n'))).toContain('QUESTION')
    expect(stripTerminalSequences(inside.join('\n'))).toContain('Ctrl+F search�')
    const dashboard = (root as unknown as {
      dashboard: { render(width: number): string[] }
    }).dashboard
    const dashboardText = stripTerminalSequences(dashboard.render(40).join('\n'))
    expect(dashboardText).toContain('WORKBENCH DASHBOARD')
    expect(dashboardText).toContain('GOAL active')
    expect(dashboardText).toContain('● render rail�')
    expect(stripTerminalSequences(dashboard.render(8).join('\n'))).toContain('WORKBENC')
    expect(layoutConversationDashboard({
      label: 'DASHBOARD',
      lines: [{ text: 'GOAL active', tone: 'accent' }],
    }, 8).map(stripTerminalSequences)).toEqual(['DASHBOAR', 'GOAL act'])
    expect(layoutConversationDashboard({ label: 'DASHBOARD', lines: [] }, 40))
      .toHaveLength(3)
    const statusline = (root as unknown as {
      statusline: { render(width: number): string[] }
    }).statusline
    const statusText = stripTerminalSequences(statusline.render(40).join('\n'))
    expect(statusText).toContain('◆ MODEL deepseek/high')
    expect(statusText).toContain('CTX [━━━━····]')
    expect(statusText).not.toContain('\u0007')
    for (const line of inside) expect(visibleWidth(line)).toBeLessThanOrEqual(24)
    root.component.invalidate()

    root.setSurface({
      ...surface('中文-session', 1, []),
      composer: '',
      composerColumn: 99,
      composerPrefix: '> ',
    })
    expect(statusline.render(40)).toEqual([])
    expect(dashboard.render(40)).toEqual([])
    expect(root.component.render(8).join('\n')).toContain('\x1b_pi:c\u0007')
    root.deactivate()
    root.dispose()
    root.captureBeforeResize()
    root.deactivate()
    expect(root.restoreAfterLayout()).toBe(false)
  })

  it('keeps every focused question option visible above a long transcript', () => {
    const root = new ConversationRoot(mono, () => {})
    root.setSurface({
      ...surface('question-options', 1, [{
        kind: 'tool',
        key: 'tool:running',
        revision: '1',
        label: 'TOOL · ask_user_question',
        status: 'running',
        lines: Array.from({ length: 100 }, (_, index) => `tool line ${index + 1}`),
      }]),
      dock: {
        label: 'QUESTION',
        role: 'interaction',
        lines: [
          'Answering question 1/1',
          'Toolchain: Choose the accepted fixture option.',
          '1. Alpha — First fixture option.',
          '2. Beta — Expected fixture option.',
        ],
      },
      statusline: { text: 'ctx 80/1M 0%', tone: 'muted' },
      composerPrefix: 'answer> ',
      footer: 'Question 1/1: Enter answer · Esc cancel',
    })

    const output = stripTerminalSequences(
      renderLayoutFrame(root.component, 100, 30, () => {}).lines.join('\n'),
    )
    expect(output).toContain('1. Alpha — First fixture option.')
    expect(output).toContain('2. Beta — Expected fixture option.')
    root.dispose()
  })

  it('orders and colors Dashboard, Timeline, Decision, Composer, and Statusline as separate zones', () => {
    const cordis = createDshTuiTheme({ preset: 'cordis' }, {
      colorSupported: true,
      noColor: false,
      dumbTerminal: false,
    })
    const root = new ConversationRoot(cordis, () => {})
    root.setSurface({
      ...surface('zones', 1, [assistant('assistant:zones', 'timeline answer')]),
      dashboard: {
        label: 'WORKBENCH DASHBOARD',
        lines: [{ text: 'GOAL ACTIVE · PLAN ON · TODO 1/2', tone: 'accent' }],
      },
      dock: { label: 'APPROVAL', role: 'interaction', lines: ['Allow workspace read?'] },
      statusline: {
        text: '◆ MODEL deepseek/high · CTX 25%',
        tone: 'muted',
        segments: [
          { text: 'MODEL deepseek/high', tone: 'assistant' },
          { text: 'CTX 25%', tone: 'telemetry' },
        ],
      },
      composerLabel: 'PROMPT',
      composerBoxed: true,
    })

    const internals = root as unknown as {
      dashboard: { render(width: number): string[] }
      dock: { render(width: number): string[] }
      statusline: { render(width: number): string[] }
      composer: { render(width: number): string[] }
    }
    expect(internals.dashboard.render(80).join('\n')).toContain('\u001b[36m')
    expect(internals.dock.render(80).join('\n')).toContain('\u001b[95m')
    expect(internals.statusline.render(80).join('\n')).toContain('\u001b[96m')
    expect(internals.composer.render(80).join('\n')).toContain('\u001b[94m')

    const visible = stripTerminalSequences(
      renderLayoutFrame(root.component, 80, 24, () => {}).lines.join('\n'),
    )
    const zones = [
      'WORKBENCH DASHBOARD',
      'timeline answer',
      'APPROVAL',
      'PROMPT',
      '◆ MODEL',
    ].map(marker => visible.indexOf(marker))
    expect(zones.every(index => index >= 0)).toBe(true)
    expect(zones).toEqual([...zones].sort((left, right) => left - right))
    root.dispose()
  })

  it('paints trusted Tool syntax segments in compact and bordered cards', () => {
    const theme = createDshTuiTheme({ preset: 'cordis' }, {
      colorSupported: true,
      noColor: false,
      dumbTerminal: false,
    })
    const root = new ConversationRoot(theme, () => {})
    root.setSurface(surface('styled-tool', 1, [{
      kind: 'tool',
      key: 'tool:styled',
      revision: '1',
      label: 'TOOL read',
      status: 'done',
      lines: ['const answer'],
      styledLines: [{ segments: [
        { text: 'const', tone: 'accent', bold: true },
        { text: ' answer', tone: 'code' },
      ] }],
    }]))

    const document = (root as unknown as {
      document: { render(width: number): string[] }
    }).document
    for (const width of [8, 40]) {
      const rendered = document.render(width).join('\n')
      expect(rendered).toContain('\u001b')
      expect(stripTerminalSequences(rendered)).toContain('const')
    }
    root.dispose()
  })

  it('renders the command shelf without card chrome and omits an empty footer', () => {
    const theme = createDshTuiTheme({ preset: 'cordis' }, {
      colorSupported: true,
      noColor: false,
      dumbTerminal: false,
    })
    const root = new ConversationRoot(theme, () => {})
    root.setSurface({
      ...surface('command-shelf', 1, []),
      footer: '',
      dock: {
        label: 'COMMANDS',
        role: 'command',
        lines: ['/mode  Switch mode', '/model  Switch model'],
        styledLines: [{
          segments: [
            { text: '/mode', tone: 'accent', bold: true },
            { text: '  Switch mode', tone: 'primary' },
          ],
        }],
      },
    })

    const internals = root as unknown as {
      dock: { render(width: number): string[] }
      footer: { render(width: number): string[] }
    }
    const rendered = internals.dock.render(40)
    const plain = stripTerminalSequences(rendered.join('\n'))
    expect(plain).toContain('/mode  Switch mode')
    expect(plain).toContain('/model  Switch model')
    expect(plain).not.toContain('COMMANDS')
    expect(rendered.join('\n')).toContain('\u001b')
    expect(internals.footer.render(40)).toEqual([])
    root.dispose()
  })

  it('renders a multiline composer as real terminal rows instead of flattening newlines', () => {
    const root = new ConversationRoot(mono, () => {})
    root.setSurface({
      ...surface('multiline', 1, []),
      composer: 'first line\nsecond line',
      composerColumn: 22,
      composerPrefix: '> ',
      composerLabel: 'PROMPT',
      composerBoxed: true,
    })

    const output = root.component.render(24).map(stripTerminalSequences)
    expect(output.some(line => line.includes('╭─ PROMPT'))).toBe(true)
    expect(output.some(line => line.includes('> first line'))).toBe(true)
    expect(output.some(line => line.includes('  second line'))).toBe(true)
    expect(output.some(line => line.includes('first line second line'))).toBe(false)
    const composer = (root as unknown as {
      composer: { render(width: number): string[] }
    }).composer
    expect(composer.render(1).every(line => visibleWidth(line) <= 1)).toBe(true)
    const clipped = layoutConversationComposer(
      'one\ntwo\nthree\nfour\nfive\nsix',
      4,
      '> ',
      'PROMPT',
      true,
      20,
    )
    expect(clipped.lines).toHaveLength(6)
    expect(clipped.cursor).toBeDefined()
    root.dispose()
  })

  it('restores a deliberately frozen empty document without inventing an anchor', () => {
    const root = new ConversationRoot(mono, () => {})
    root.setSurface(surface('empty', 1, []))
    layout(root)
    root.scroll.scrollTo(0, { disableFollow: true })
    root.setSurface({
      ...surface('empty', 1, []),
      footer: 'changed revision source',
      nodes: [{ kind: 'notice', key: 'notice', revision: '1', lines: [] }],
    })
    root.document.render(20)
    root.scroll.updateLayout(0, 5, () => {})
    expect(root.restoreAfterLayout()).toBe(false)
    expect(root.scroll.isFollowingEnd).toBe(false)

    const dock = (root as unknown as {
      dock: { render(width: number): string[] }
    }).dock
    root.setSurface(surface('empty', 1, []))
    expect(dock.render(20)).toEqual([])
    root.dispose()
  })

  it('terminates defensively if a corrupted snapshot iterator cannot yield an LRU key', () => {
    const root = new ConversationRoot(mono, () => {})
    root.setSurface(surface('active', 1, []))
    const snapshots = (root as unknown as {
      snapshots: Map<string, unknown>
    }).snapshots
    for (let index = 0; index < 33; index += 1) snapshots.set(`snapshot-${index}`, {})
    snapshots.keys = () => ({
      next: () => ({ done: true, value: undefined }),
    }) as MapIterator<string>

    expect(() => root.setSurface(surface('next', 1, []))).not.toThrow()
    expect(snapshots.size).toBeGreaterThan(32)
    root.dispose()
  })

  it('keeps the fixed header renderable when bold styling is disabled', () => {
    const root = new ConversationRoot(mono, () => {})
    root.setSurface(surface('plain-header', 1, []))
    const header = (root as unknown as {
      header: { bold: boolean; render(width: number): string[] }
    }).header
    header.bold = false
    expect(header.render(12)).toHaveLength(1)
    expect(visibleWidth(header.render(12)[0]!)).toBeLessThanOrEqual(12)
    root.dispose()
  })

  it('honors an explicit follow request in-place and after restoring a remembered session', () => {
    const root = new ConversationRoot(mono, () => {})
    const many = Array.from({ length: 14 }, (_, index) => assistant(
      `assistant:${index}`,
      `message ${index}`,
    ))
    root.setSurface({ ...surface('A', 1, many), followRequest: 0 })
    root.setSurface({ ...surface('A', 1, many), followRequest: 0 })
    layout(root)
    root.scroll.scrollTo(4, { disableFollow: true })

    root.setSurface({
      ...surface('A', 1, [...many, assistant('assistant:late', 'late')]),
      followRequest: 1,
    })
    layout(root)
    expect(root.scroll.isFollowingEnd).toBe(true)

    root.scroll.scrollTo(4, { disableFollow: true })
    root.setSurface({ ...surface('B', 1, many), followRequest: 0 })
    layout(root)
    root.setSurface({ ...surface('A', 2, many), followRequest: 2 })
    layout(root)
    expect(root.scroll.isFollowingEnd).toBe(true)
    root.dispose()
  })
})

describe('markdown source safety', () => {
  it('downgrades relative, custom, and overlong destinations to visible text', () => {
    const long = 'https://example.com/' + 'x'.repeat(2050)
    const output = sanitizeMarkdownSource(
      `[relative](./a) [custom](dsh:run) [long](${long})`,
    )
    expect(output).toContain('relative (./a)')
    expect(output).toContain('custom (dsh:run)')
    expect(output).toContain('long (https://example.com/')
  })

  it('filters unsafe definitions, images, and autolinks while retaining safe URLs', () => {
    const output = sanitizeMarkdownSource([
      '[safe]: <https://example.com/path> "title"',
      '[bad]: javascript:alert(1)',
      '![bad image](file:///C:/secret)',
      '![](file:///C:/secret)',
      '[empty]()',
      '<javascript:alert(1)>',
      '<mailto:test@example.com>',
      '\x1bPowned\x1b\\tab\tcontrol\u0001',
    ].join('\r\n'))

    expect(output).toContain('[safe]: <https://example.com/path> "title"')
    expect(output).not.toContain('[bad]:')
    expect(output).toContain('[image: bad image]')
    expect(output).toContain('[image: attachment]')
    expect(output).toContain('empty')
    expect(output).toContain('javascript:alert(1)')
    expect(output).toContain('<mailto:test@example.com>')
    expect(output).toContain('tab  control�')
    expect(output).not.toContain('\x1b')
  })

  it('retains a visible URL when terminal hyperlinks are unavailable', () => {
    setCapabilities({ images: null, trueColor: false, hyperlinks: false })
    const document = new ConversationDocumentComponent(mono)
    document.setNodes([{
      kind: 'assistant',
      key: 'assistant:link',
      revision: '1',
      text: '[documentation](https://example.com/docs)',
    }], false)
    expect(stripTerminalSequences(document.render(80).join('\n')))
      .toContain('https://example.com/docs')
  })

  it('removes an unsafe OSC 8 target injected by a presentation formatter', () => {
    setCapabilities({ images: null, trueColor: false, hyperlinks: false })
    const hostileTheme = {
      ...mono,
      paint: (role: Parameters<typeof mono.paint>[0], value: string): string => (
        role === 'muted'
          ? `\x1b]8;;javascript:owned\x1b\\${value}\x1b]8;;\x1b\\`
          : value
      ),
    }
    const document = new ConversationDocumentComponent(hostileTheme)
    document.setNodes([{
      kind: 'assistant',
      key: 'assistant:formatter-link',
      revision: '1',
      text: '[documentation](https://example.com/docs)',
    }], false)
    const output = document.render(10).join('\n')
    expect(output).not.toContain('javascript:owned')
    expect(stripTerminalSequences(output)).toContain('documentat')
  })
})
